version: '3'
services:
  my-node-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./main.js:/app/main.js  # Mount the main.js file
      - ./package.json:/app/package.json  # Mount the package.json file
